### ISSUE TITLE
Projects

### ISSUE THREAD

**Issue by TobiasRoeddiger** [teco-kit/explorer-frontend#7]
Projects will allow the user to manage access to datasets better.

A project has the following features:
- users can access the project 
- datasets, that are part of the project and can be accessed by all members of the project 
- all members of a project can add datasets to that project 
- all users can also delete and edit any dataset similar to the admin of the project 

The creator of a project is an admin that can
- add new members to the project 
- remove members from the project 
- rename a project 
- currently, no other rights are planned (e.g., multiple admins, edit permission, etc.), but we might keep that in mind during the design

Some visual suggestions:
- projects can be selected as a dropdown menu from the navigation bar next to the explorer tag
- settings are available on a per project basis

**Comment by tk-king** [comment]
In addition:

- Move settings from the top left little icon to the main settings page
- Improve user account handling: Add dropdown to top right corner with Logout, user settings, ...

**Comment by TobiasRoeddiger** [comment]
- added data structure to realize projects
- frontend handles the new project-based format



- need to finalize project user management

**Comment by TobiasRoeddiger** [comment]
Features completed, testing pending for the next days.
